### ISSUE TITLE
2nd column in Standards types in Org settings

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#111]
The 2nd column values in the Standards types subcard in Org settings (e.g. "PRO", "SOP", "WORK") are not used anywhere in the system and confuse users.   Let's just delete this column and have a single column of fields in this subcard.

**Comment by sives** [comment]
On reflection, since this feature will be used in an upcoming release, let's just leave it in as originally specified and get it working properly (i.e. make the filling-in of the 2nd column values mandatory and check that abbreviation in 2nd column is no more than 4 characters long).   Related to issue 155, Risk types, which uses the same subcard and has the same problem.

**Comment by Praxie** [comment]
Fixed

**Comment by sives** [comment]
To ensure that the abbreviation is not longer than 4 letters, we should stop the user entering the 5th character in the field, not allow it and then display an error message at the top.  Then it's much more obvious to the user what they are doing wrong with their data entry.

**Comment by Praxie** [comment]
> We should make this a consistent behaviour across the system whenever the user tries to type in more text than the field text limit allows.

@sives This should be an "enhancement" issue.

**Comment by Praxie** [comment]
> To ensure that the abbreviation is not longer than 4 letters, we should stop the user entering the 5th character in the field

@sives Implemented in the current release.
