### ISSUE TITLE
Change "Book section" field label in Standards card

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#121]
Change the field label "Book section" to "Standards section" in the Compliance standards card.

Make sure that the dropdown list that is displayed when you click on this field is large enough to display at least 12 selection items (at the moment you can only view 7, which is too few)

Also to match up with the field label change, change "Standards book sections" to "Compliance standards sections" in the relevant subcard in the Org settings screen.

**Comment by sives** [comment]
2nd part of this issue is not done yet 

[Make sure that the dropdown list that is displayed when you click on this field is large enough to display at least 12 selection items (at the moment you can only view 7, which is too few)]

![screen shot 2016-10-05 at 16 24 37](https://cloud.githubusercontent.com/assets/2330529/19119622/456f2da6-8b18-11e6-8fd8-51b342d598c9.png)

**Comment by Praxie** [comment]
**v0.2.36** feature

**Comment by sives** [comment]
Looks good.
