### ISSUE TITLE
Org settings card close bug

### ISSUE THREAD

**Issue by sives** [sives/Plio#134]
When you add a new Risk type to the Risk types subcard and click on "Close" at the top of the card, the card closes before displaying the "Saving..." message in the header bar - so the user has no positive confirmation about whether data has been saved or not.

**Comment by Praxie** [comment]
@sives the "Saving..." message is displaying when the text input loses focus. So if you will keep a cursor inside of the risk type field (Title or Short) and click on the Close button, the "Saving..." message will appear. If you will click on any other white area in page, the "Saving..." message will be displayed immediately and it even if you won't see it by being at the bottom of the card. We could have another "Saving" indicator (a "Saving..." notification or a floppy icon) in the corner of the page so that it would be always visible to the user.

**Comment by sives** [comment]
This explanation is not consistent with the behaviour of the Close button in other parts of the system, where you do get a Saving.. message in the card header after you've made a change in the card.   

The observed behaviour here is related to Issue 155.  If we fix issue 155, then this issue will go away.

**Comment by Praxie** [comment]
@sives so can we consider this issue resolved as an issue 155 is fixed?

**Comment by sives** [comment]
Yes
