### ISSUE TITLE
Access control error - You have no access to organisation 98

### ISSUE THREAD

**Issue by sives** [sives/Plio#71]
I'm getting this error message "You have no access to organisation 98" after logging in with steve.ives@pliohub.com  pw=password.  I get to the Home screen but when I try to go into the Standards screen it gives me that message.  Same when I try to login with other credentials e.g. Michael.Rokosh@pliohub.com.  

When I login sometimes it is taking me directly to the Standards screen rather than the Home screen, which is strange.

**Comment by Praxie** [comment]
@sives I can't confirm this issue.
> "You have no access to organisation 98"

Maybe you tried to log in during the deployment or after the database was reset. Can you reproduce this bug now?

> When I login sometimes it is taking me directly to the Standards screen rather than the Home screen, which is strange.

This is a proper behaviour. If you are logged out and you're trying to open the Standard List view (e.g. https://app.pliohub.com/98/standards/Zty4NCagWvrcuLYoy) you'll be redirected to the sign in page and the target url will be remembered so that after a successful sign in you could be redirected to the Standard List view that you tried to open before. (Rather than the Home screen)

**Comment by sives** [comment]
I have seen this error message again today.  I can't exactly reproduce the circumstances.

Also, I saw this similar error, for a different organization name.  Not sure how this could have happened, since I wasn't trying to access anything in the organization called NaN.

![screen shot 2016-05-27 at 13 46 27](https://cloud.githubusercontent.com/assets/2330529/15610058/496a0dd6-241b-11e6-9b4f-691b52c5e0be.png)

**Comment by Praxie** [comment]
> Also, I saw this similar error, for a different organization name. Not sure how this could have happened, since I wasn't trying to access anything in the organization called NaN.

Fixed
